export const leagues = [
    { id: 1, name: 'Premier League' },
    { id: 2, name: 'La Liga' },
  ];
  

  export const teams = [
    { league: 1, id: 101, name: 'Manchester City' },
    { league: 1, id: 102, name: 'Liverpool' },
    { league: 1, id: 103, name: 'Chelsea' },
    { league: 1, id: 112, name: 'Fulham' },
    { league: 1, id: 104, name: 'Manchester United' },
    { league: 1, id: 105, name: 'Tottenham Hotspur' },
    { league: 1, id: 106, name: 'Newcastle United' },
    { league: 1, id: 107, name: 'West Ham United' },
    { league: 1, id: 108, name: 'Aston Villa' },
    { league: 1, id: 109, name: 'Brighton & Hove Albion' },
    { league: 1, id: 110, name: 'Wolverhampton Wanderers' },
    { league: 1, id: 111, name: 'Everton' },
    { league: 1, id: 113, name: 'Brentford' },
    { league: 1, id: 114, name: 'Burnley' },
    { league: 1, id: 115, name: 'Sheffield United' },
    { league: 1, id: 116, name: 'Nottingam Forest' },
    { league: 1, id: 117, name: 'Bournemouth' },
    { league: 1, id: 118, name: 'Luton Town' },
    { league: 1, id: 119, name: 'Crystal Palace' },
    { league: 1, id: 120, name: 'Arsenal' },
    { league: 2, id: 201, name: 'FC Barcelona' },
    { league: 2, id: 202, name: 'Real Madrid' },
    { league: 2, id: 204, name: 'Girona' },
    { league: 2, id: 205, name: 'Alavés' },
    { league: 2, id: 206, name: 'Osasuna' },
    { league: 2, id: 207, name: 'Celta Vigo' },
    { league: 2, id: 208, name: 'Leganes' },
    { league: 2, id: 209, name: 'Majorca' },
    { league: 2, id: 210, name: 'Vallecano' },
    { league: 2, id: 211, name: 'Real Sociedad' },
    { league: 2, id: 212, name: 'Atletic Club Bilbao' },
    { league: 2, id: 213, name: 'Espanyol Barcelona' },
    { league: 2, id: 219, name: 'Valladoleague: 1, id' },
    { league: 2, id: 214, name: 'Getafe' },
    { league: 2, id: 215, name: 'Betis Sevilla' },
    { league: 2, id: 216, name: 'Las Palmas' },
    { league: 2, id: 218, name: 'Valencia FC' },
    { league: 2, id: 217, name: 'Sevilla FC' },
    { league: 2, id: 220, name: 'Villareal' },
  ];

